# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$env_var\
$fill\
$python\
$lua\
$nodejs\
$golang\
$rust\
$c\
$java\
$ruby\
$swift\
$package\
$docker_context\
$jobs\
$cmd_duration\
$time\
$line_break\
$character"""

palette = 'catppuccin_mocha'

# Inserts a blank line between shell prompts
add_newline = true

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 3600000

# Ignore global command_timeout setting and keep running external commands, no matter how long they take.
# ignore_timeout = true

# Timeout for starship to scan files (in milliseconds).
scan_timeout = 500

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = true

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[kubernetes]
symbol = '󱃾 '
disabled = false

[docker_context]
disabled = true

[directory]
home_symbol = " ~"
truncation_symbol = ' '
style = "bold blue"
# truncation_length = 2
read_only = '󱧵 '
read_only_style = ''

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ' '

[git_status]
conflicted = '='
up_to_date = ''
untracked = '?${count}'
stashed = '\$${count}'
modified = '!${count}'
staged = '+${count}'
renamed = '»'
deleted = '✘'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[git_commit]
format = '[\($hash$tag\)]($style) '
style = 'bold green'
commit_hash_length = 8
disabled = false
tag_disabled = false
only_detached = false

[aws]
disabled = true

[package]
format = '[$symbol$version ]($style)'
symbol = '󰏗 '

[nodejs]
format = '[$symbol($version )]($style)'
symbol = '󰎙 '

[dotnet]
format = '[$symbol($version )]($style)'
symbol = ' '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ' '

[java]
format = '[$symbol($version )]($style)'
symbol = ' '
style = 'bold red'

[c]
format = '[$symbol($version(-$name) )]($style)'
symbol = ' '

[swift]
format = '[$symbol($version )]($style)'
symbol = ' '

[golang]
format = '[$symbol($version )]($style)'
symbol = ' '

[lua]
format = '[$symbol($version )]($style)'
symbol = ' '

[terraform]
symbol = '󱁢 '

[fill]
symbol = ' '

[cmd_duration]
min_time = 500

[shell]
unknown_indicator = 'shell'
powershell_indicator = 'powershell'
bash_indicator = 'bash'
zsh_indicator = 'zsh'
fish_indicator = 'fish'
disabled = true

[env_var.all_proxy]
format = '[${symbol}]($style) '
symbol = '󰚻 '
style = 'bold sky'

[time]
time_format = '%R %v'
style = 'bold peach'
disabled = false

[username]
show_always = true
disabled = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
vimcmd_symbol = "[➜](bold yellow)"

# [character]
## Note the use of Catppuccin color 'peach'
# success_symbol = "[[󰄛](green) ❯](peach)"
# error_symbol = "[[󰄛](red) ❯](peach)"
# vimcmd_symbol = "[󰄛 ❮](subtext1)" # For use with zsh-vi-mode
